In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [10]:
print('e^1 equals :',torch.exp(torch.FloatTensor([2])))

e^1 equals : tensor([7.3891])


In [11]:
w = torch.zeros((2,1),requires_grad = True)
b = torch.zeros(1,requires_grad = True)

In [12]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(w) + b)))

In [13]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [14]:
hypothesis = torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)


In [15]:
print(y_train)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [16]:
losses = -(y_train * torch.log(hypothesis) + (1-y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [17]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [18]:
F.binary_cross_entropy(hypothesis,y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [40]:
w = torch.zeros((2,1),requires_grad = True)
b = torch.zeros(1,requires_grad = True)

optimizer = optim.SGD([w,b],lr = 1)

nb_epochs = 100000

for epoch in range(nb_epochs + 1):
    hypothesis = torch.sigmoid(x_train.matmul(w) + b)
    cost = F.binary_cross_entropy(hypothesis,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10000 == 0:
        print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/100000 Cost : 0.693147
Epoch 10000/100000 Cost : 0.002132
Epoch 20000/100000 Cost : 0.001071
Epoch 30000/100000 Cost : 0.000715
Epoch 40000/100000 Cost : 0.000537
Epoch 50000/100000 Cost : 0.000429
Epoch 60000/100000 Cost : 0.000358
Epoch 70000/100000 Cost : 0.000307
Epoch 80000/100000 Cost : 0.000269
Epoch 90000/100000 Cost : 0.000239
Epoch 100000/100000 Cost : 0.000215


In [22]:
hypothesis = torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis[:5])

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)


In [23]:
prediction = hypothesis >= torch.FloatTensor([0.5])

In [24]:
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [25]:
print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


In [26]:
print(prediction[:5].float())

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [29]:
print(prediction[:5],'\n',y_train[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]]) 
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [30]:
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


In [31]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [32]:
model = BinaryClassifier()

In [37]:
optimizer = optim.SGD(model.parameters(),lr = 1)

nb_epochs = 10000

for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost : {:.6f} Accuracy {:2.2f}%'.format(epoch,nb_epochs,cost.item(),accuracy * 100))

Epoch    0/10000 Cost : 0.014435 Accuracy 100.00%
Epoch   10/10000 Cost : 0.014338 Accuracy 100.00%
Epoch   20/10000 Cost : 0.014243 Accuracy 100.00%
Epoch   30/10000 Cost : 0.014149 Accuracy 100.00%
Epoch   40/10000 Cost : 0.014056 Accuracy 100.00%
Epoch   50/10000 Cost : 0.013964 Accuracy 100.00%
Epoch   60/10000 Cost : 0.013874 Accuracy 100.00%
Epoch   70/10000 Cost : 0.013785 Accuracy 100.00%
Epoch   80/10000 Cost : 0.013697 Accuracy 100.00%
Epoch   90/10000 Cost : 0.013610 Accuracy 100.00%
Epoch  100/10000 Cost : 0.013524 Accuracy 100.00%
Epoch  110/10000 Cost : 0.013439 Accuracy 100.00%
Epoch  120/10000 Cost : 0.013355 Accuracy 100.00%
Epoch  130/10000 Cost : 0.013273 Accuracy 100.00%
Epoch  140/10000 Cost : 0.013191 Accuracy 100.00%
Epoch  150/10000 Cost : 0.013110 Accuracy 100.00%
Epoch  160/10000 Cost : 0.013031 Accuracy 100.00%
Epoch  170/10000 Cost : 0.012952 Accuracy 100.00%
Epoch  180/10000 Cost : 0.012874 Accuracy 100.00%
Epoch  190/10000 Cost : 0.012797 Accuracy 100.00%


Epoch 2040/10000 Cost : 0.006088 Accuracy 100.00%
Epoch 2050/10000 Cost : 0.006071 Accuracy 100.00%
Epoch 2060/10000 Cost : 0.006054 Accuracy 100.00%
Epoch 2070/10000 Cost : 0.006037 Accuracy 100.00%
Epoch 2080/10000 Cost : 0.006020 Accuracy 100.00%
Epoch 2090/10000 Cost : 0.006003 Accuracy 100.00%
Epoch 2100/10000 Cost : 0.005986 Accuracy 100.00%
Epoch 2110/10000 Cost : 0.005970 Accuracy 100.00%
Epoch 2120/10000 Cost : 0.005953 Accuracy 100.00%
Epoch 2130/10000 Cost : 0.005937 Accuracy 100.00%
Epoch 2140/10000 Cost : 0.005920 Accuracy 100.00%
Epoch 2150/10000 Cost : 0.005904 Accuracy 100.00%
Epoch 2160/10000 Cost : 0.005888 Accuracy 100.00%
Epoch 2170/10000 Cost : 0.005872 Accuracy 100.00%
Epoch 2180/10000 Cost : 0.005856 Accuracy 100.00%
Epoch 2190/10000 Cost : 0.005840 Accuracy 100.00%
Epoch 2200/10000 Cost : 0.005824 Accuracy 100.00%
Epoch 2210/10000 Cost : 0.005808 Accuracy 100.00%
Epoch 2220/10000 Cost : 0.005793 Accuracy 100.00%
Epoch 2230/10000 Cost : 0.005777 Accuracy 100.00%


Epoch 4060/10000 Cost : 0.003873 Accuracy 100.00%
Epoch 4070/10000 Cost : 0.003866 Accuracy 100.00%
Epoch 4080/10000 Cost : 0.003859 Accuracy 100.00%
Epoch 4090/10000 Cost : 0.003852 Accuracy 100.00%
Epoch 4100/10000 Cost : 0.003845 Accuracy 100.00%
Epoch 4110/10000 Cost : 0.003838 Accuracy 100.00%
Epoch 4120/10000 Cost : 0.003832 Accuracy 100.00%
Epoch 4130/10000 Cost : 0.003825 Accuracy 100.00%
Epoch 4140/10000 Cost : 0.003818 Accuracy 100.00%
Epoch 4150/10000 Cost : 0.003811 Accuracy 100.00%
Epoch 4160/10000 Cost : 0.003805 Accuracy 100.00%
Epoch 4170/10000 Cost : 0.003798 Accuracy 100.00%
Epoch 4180/10000 Cost : 0.003791 Accuracy 100.00%
Epoch 4190/10000 Cost : 0.003784 Accuracy 100.00%
Epoch 4200/10000 Cost : 0.003778 Accuracy 100.00%
Epoch 4210/10000 Cost : 0.003771 Accuracy 100.00%
Epoch 4220/10000 Cost : 0.003765 Accuracy 100.00%
Epoch 4230/10000 Cost : 0.003758 Accuracy 100.00%
Epoch 4240/10000 Cost : 0.003751 Accuracy 100.00%
Epoch 4250/10000 Cost : 0.003745 Accuracy 100.00%


Epoch 6110/10000 Cost : 0.002829 Accuracy 100.00%
Epoch 6120/10000 Cost : 0.002825 Accuracy 100.00%
Epoch 6130/10000 Cost : 0.002821 Accuracy 100.00%
Epoch 6140/10000 Cost : 0.002818 Accuracy 100.00%
Epoch 6150/10000 Cost : 0.002814 Accuracy 100.00%
Epoch 6160/10000 Cost : 0.002810 Accuracy 100.00%
Epoch 6170/10000 Cost : 0.002807 Accuracy 100.00%
Epoch 6180/10000 Cost : 0.002803 Accuracy 100.00%
Epoch 6190/10000 Cost : 0.002799 Accuracy 100.00%
Epoch 6200/10000 Cost : 0.002796 Accuracy 100.00%
Epoch 6210/10000 Cost : 0.002792 Accuracy 100.00%
Epoch 6220/10000 Cost : 0.002788 Accuracy 100.00%
Epoch 6230/10000 Cost : 0.002785 Accuracy 100.00%
Epoch 6240/10000 Cost : 0.002781 Accuracy 100.00%
Epoch 6250/10000 Cost : 0.002778 Accuracy 100.00%
Epoch 6260/10000 Cost : 0.002774 Accuracy 100.00%
Epoch 6270/10000 Cost : 0.002770 Accuracy 100.00%
Epoch 6280/10000 Cost : 0.002767 Accuracy 100.00%
Epoch 6290/10000 Cost : 0.002763 Accuracy 100.00%
Epoch 6300/10000 Cost : 0.002760 Accuracy 100.00%


Epoch 8110/10000 Cost : 0.002240 Accuracy 100.00%
Epoch 8120/10000 Cost : 0.002237 Accuracy 100.00%
Epoch 8130/10000 Cost : 0.002235 Accuracy 100.00%
Epoch 8140/10000 Cost : 0.002233 Accuracy 100.00%
Epoch 8150/10000 Cost : 0.002230 Accuracy 100.00%
Epoch 8160/10000 Cost : 0.002228 Accuracy 100.00%
Epoch 8170/10000 Cost : 0.002226 Accuracy 100.00%
Epoch 8180/10000 Cost : 0.002223 Accuracy 100.00%
Epoch 8190/10000 Cost : 0.002221 Accuracy 100.00%
Epoch 8200/10000 Cost : 0.002219 Accuracy 100.00%
Epoch 8210/10000 Cost : 0.002217 Accuracy 100.00%
Epoch 8220/10000 Cost : 0.002214 Accuracy 100.00%
Epoch 8230/10000 Cost : 0.002212 Accuracy 100.00%
Epoch 8240/10000 Cost : 0.002210 Accuracy 100.00%
Epoch 8250/10000 Cost : 0.002208 Accuracy 100.00%
Epoch 8260/10000 Cost : 0.002205 Accuracy 100.00%
Epoch 8270/10000 Cost : 0.002203 Accuracy 100.00%
Epoch 8280/10000 Cost : 0.002201 Accuracy 100.00%
Epoch 8290/10000 Cost : 0.002198 Accuracy 100.00%
Epoch 8300/10000 Cost : 0.002196 Accuracy 100.00%


In [45]:
b = torch.zeros(1,requires_grad = True)
print(b)

tensor([0.], requires_grad=True)
