In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import torch.optim as optim
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

torch.manual_seed(1)

x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [2]:
model = nn.Sequential(
        nn.Linear(2,1),
        nn.Sigmoid()
)

In [3]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward>)

In [11]:
optimizer = optim.SGD(model.parameters(),lr = 1)

nb_epochs = 10000

for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d} / {} Cost : {:.6f} Accuracy {:2.2f}%'.format(epoch,nb_epochs,cost.item(),accuracy * 100))

Epoch    0 / 10000 Cost : 0.019806 Accuracy 100.00%
Epoch 1000 / 10000 Cost : 0.010293 Accuracy 100.00%
Epoch 2000 / 10000 Cost : 0.006959 Accuracy 100.00%
Epoch 3000 / 10000 Cost : 0.005257 Accuracy 100.00%
Epoch 4000 / 10000 Cost : 0.004224 Accuracy 100.00%
Epoch 5000 / 10000 Cost : 0.003531 Accuracy 100.00%
Epoch 6000 / 10000 Cost : 0.003033 Accuracy 100.00%
Epoch 7000 / 10000 Cost : 0.002658 Accuracy 100.00%
Epoch 8000 / 10000 Cost : 0.002366 Accuracy 100.00%
Epoch 9000 / 10000 Cost : 0.002131 Accuracy 100.00%
Epoch 10000 / 10000 Cost : 0.001939 Accuracy 100.00%


In [12]:
model(x_train)

tensor([[8.4220e-07],
        [3.2344e-03],
        [3.7878e-03],
        [9.9543e-01],
        [9.9998e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward>)

In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[5.5572, 2.6994]], requires_grad=True), Parameter containing:
tensor([-24.9432], requires_grad=True)]


In [15]:
model =nn.Sequential(
        nn.Linear(2,1),
        nn.Sigmoid()
)

In [16]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [17]:
model = BinaryClassifier()

optimizer = optim.SGD(model.parameters(),lr = 1)

nb_epochs = 1000

for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d} / {} Cost : {:.6f} Accuracy {:2.2f}%'.format(epoch,nb_epochs,cost.item(),accuracy * 100))

Epoch    0 / 1000 Cost : 0.614994 Accuracy 66.67%
Epoch   10 / 1000 Cost : 0.747550 Accuracy 83.33%
Epoch   20 / 1000 Cost : 0.633216 Accuracy 83.33%
Epoch   30 / 1000 Cost : 0.538123 Accuracy 83.33%
Epoch   40 / 1000 Cost : 0.450406 Accuracy 83.33%
Epoch   50 / 1000 Cost : 0.366382 Accuracy 83.33%
Epoch   60 / 1000 Cost : 0.287368 Accuracy 83.33%
Epoch   70 / 1000 Cost : 0.219288 Accuracy 83.33%
Epoch   80 / 1000 Cost : 0.173225 Accuracy 100.00%
Epoch   90 / 1000 Cost : 0.151674 Accuracy 100.00%
Epoch  100 / 1000 Cost : 0.140280 Accuracy 100.00%
Epoch  110 / 1000 Cost : 0.131002 Accuracy 100.00%
Epoch  120 / 1000 Cost : 0.122903 Accuracy 100.00%
Epoch  130 / 1000 Cost : 0.115765 Accuracy 100.00%
Epoch  140 / 1000 Cost : 0.109426 Accuracy 100.00%
Epoch  150 / 1000 Cost : 0.103760 Accuracy 100.00%
Epoch  160 / 1000 Cost : 0.098664 Accuracy 100.00%
Epoch  170 / 1000 Cost : 0.094056 Accuracy 100.00%
Epoch  180 / 1000 Cost : 0.089870 Accuracy 100.00%
Epoch  190 / 1000 Cost : 0.086050 Accur