In [3]:
pip install --upgrade pip

  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Note: you may need to restart the kernel to use updated packages.


In [5]:
conda update -y pip


Solving environment: ...working... 

Updating pip is constricted by 

anaconda -> requires pip==20.0.2=py37_1

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

## Package Plan ##

  environment location: D:\anaconda

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    absl-py-0.13.0             |   py37haa95532_0         174 KB
    asgiref-3.3.4              |     pyhd3eb1b0_0          24 KB
    astor-0.8.1                |   py37haa95532_0          47 KB
    backports.functools_lru_cache-1.6.4|     pyhd3eb1b0_0           9 KB
    backports.tempfile-1.0     |     pyhd3eb1b0_1          11 KB
    conda-4.10.1               |   py37haa95532_1         2.9 MB
    conda-package-handling-1.7.3|   py37h8cc25b3_1         721 KB
    g

In [8]:
import torch
import numpy as np

In [9]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [14]:
print(t.ndim) 
# 몇 차원이냐
print(t.shape)
# 몇 개의 element

1


In [18]:
t = np.array([[1,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [19]:
print(t.ndim)
print(t.shape) # 4x3을 이룬다해서 (4,3)

2
(4, 3)


In [20]:
#1D Array with Pytorch
t = torch.FloatTensor([0,1,2,3,4,5,6])
#Float형태로 Tensor를 만들겠다
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [21]:
print(t.dim())
print(t.shape) # 몇 개의 element
print(t.size()) # 몇 개의 element

1
torch.Size([7])
torch.Size([7])


In [22]:
t = torch.FloatTensor([[1,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [23]:
print(t.dim())
print(t.shape) # 몇 개의 element
print(t.size()) # 몇 개의 element

2
torch.Size([4, 3])
torch.Size([4, 3])


In [24]:
print(t[:1])

tensor([[1., 2., 3.]])


In [25]:
print(t[:,1])

tensor([ 2.,  5.,  8., 11.])


In [26]:
print(t[:,1].size())
print(t[:,:-1])

torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [27]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1+m2)

tensor([5., 5.])


In [29]:
m1 = torch.FloatTensor([[1,2]])

In [30]:
m2 = torch.FloatTensor([3]) # 3 ->[[3,3]]
print(m1 +m2)
#vector + scalar

tensor([[4., 5.]])


In [31]:
m1 = torch.FloatTensor([[1,2]]) # m1 = (1,2) - > (2,2)
m2 = torch.FloatTensor([[3],[4]]) # m2 = (2,1) -> (2,2)
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [32]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [33]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1 * m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [34]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [36]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.mean())

tensor(2.5000)


In [38]:
print(t.mean(dim = 0))

tensor([2., 3.])


In [39]:
print(t.mean(dim = 1))

tensor([1.5000, 3.5000])


In [40]:
print(t.mean(dim = -1))

tensor([1.5000, 3.5000])


In [42]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [43]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [45]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [46]:
print(t.max())

tensor(4.)


In [47]:
print(t.max(dim = 0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [48]:
print(t.max(dim = 1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [49]:
print(t.max(dim = 0)[0]) # max

tensor([3., 4.])


In [50]:
print(t.max(dim = 0)[1]) # argmax

tensor([1, 1])
