In [2]:
# 2강
import numpy as np
import torch

In [3]:
#reshap 다시 모양을 만든다 == View(pytorch)
#squeeze 자동으로 1인 경우에 없애줌 디멘젼의 엘리멘트의 개수가 1인 경우를 없애줌
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [4]:
print(t)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
ft = torch.FloatTensor(t)

In [6]:
print(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [7]:
print(ft.shape)

torch.Size([2, 2, 3])


In [8]:
print(ft.view([-1,3])) #ft라는 텐서를 (?,3)의 크기로 변경

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [9]:
print(ft.view([-1,3]).shape)

torch.Size([4, 3])


In [10]:
#view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
#파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [11]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [13]:
print(ft.squeeze().shape)

torch.Size([3])


In [14]:
#unsqueeze

ft = torch.Tensor([0,1,2])
print(ft)

tensor([0., 1., 2.])


In [15]:
print(ft.shape)

torch.Size([3])


In [16]:
print(ft.unsqueeze(0))

tensor([[0., 1., 2.]])


In [17]:
print(ft.unsqueeze(0).shape)

torch.Size([1, 3])


In [19]:
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [20]:
print(ft.unsqueeze(1).shape)

torch.Size([3, 1])


In [21]:
print(ft.unsqueeze(-1))

tensor([[0.],
        [1.],
        [2.]])


In [22]:
#view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절합니다.

In [23]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [24]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [25]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [26]:
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [27]:
bt.long()

tensor([1, 0, 0, 1])

In [28]:
bt.float()

tensor([1., 0., 0., 1.])

In [29]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [30]:
z = torch.cat([x,y],dim = 0)

In [31]:
print(z.shape)

torch.Size([4, 2])


In [32]:
z

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [33]:
zz = torch.cat([x,y],dim = 1)

In [34]:
zz

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [35]:
print(zz.shape)

torch.Size([2, 4])


In [36]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [37]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [38]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [39]:
print(torch.stack([x,y,z],dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [40]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [41]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [43]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
x = torch.FloatTensor([[1,2],[3,4]])

In [45]:
print(x.mul(2))

tensor([[2., 4.],
        [6., 8.]])


In [46]:
print(x * 2)

tensor([[2., 4.],
        [6., 8.]])


In [47]:
x

tensor([[1., 2.],
        [3., 4.]])

In [48]:
print(x.mul_(2))

tensor([[2., 4.],
        [6., 8.]])


In [49]:
print(x)

tensor([[2., 4.],
        [6., 8.]])
