In [1]:
import torch
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)


In [2]:
z = torch.FloatTensor([1,2,3])


In [3]:
hypothesis = F.softmax(z,dim = 0)
print(hypothesis)


tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum().float(())


tensor(1.)

In [6]:
z= torch.rand(3,5,requires_grad = True)

In [11]:
hypothesis = F.softmax(z,dim = 1)

In [15]:
y = torch.randint(5,(3,)).long()
print(y)

tensor([3, 1, 4])


In [16]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
print(y)

tensor([3, 1, 4])


In [18]:
print(y.unsqueeze(1))

tensor([[3],
        [1],
        [4]])


In [19]:
y_one_hot2 = torch.zeros_like(hypothesis)
print(y_one_hot2)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [20]:
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [21]:
y_one_hot2.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot2)

tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])


In [22]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim = 1).mean()
print(cost)

tensor(1.6160, grad_fn=<MeanBackward0>)


In [23]:
print(z)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)


In [24]:
torch.log(F.softmax(z,dim = 1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward>)

In [25]:
F.log_softmax(z,dim = 1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [26]:
(y_one_hot * -F.log_softmax(z,dim = 1)).sum(dim = 1).mean()

tensor(1.6160, grad_fn=<MeanBackward0>)

In [27]:
F.nll_loss(F.log_softmax(z,dim = 1),y)

tensor(1.6160, grad_fn=<NllLossBackward>)