In [1]:
import torch

In [8]:
w = torch.tensor(2.0,requires_grad = True)

In [9]:
y = w ** 2
z = 2 * y + 5

In [10]:
z.backward()

In [11]:
print(w.grad)

tensor(8.)


In [12]:
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [13]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

model = nn.Linear(1,1)

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [15]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [26]:
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

nb_epochs = 1000

for epoch in range(nb_epochs + 1):
    prediction1 = model(x_train)
    cost = F.mse_loss(prediction1,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d} / {} cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0 / 1000 cost : 0.000000
Epoch  100 / 1000 cost : 0.000000
Epoch  200 / 1000 cost : 0.000000
Epoch  300 / 1000 cost : 0.000000
Epoch  400 / 1000 cost : 0.000000
Epoch  500 / 1000 cost : 0.000000
Epoch  600 / 1000 cost : 0.000000
Epoch  700 / 1000 cost : 0.000000
Epoch  800 / 1000 cost : 0.000000
Epoch  900 / 1000 cost : 0.000000
Epoch 1000 / 1000 cost : 0.000000


In [30]:
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var)

print("훈련 후 입력이 4일 때의 예측 값",pred_y)

훈련 후 입력이 4일 때의 예측 값 tensor([[8.0000]], grad_fn=<AddmmBackward>)


In [31]:
,print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([6.4333e-06], requires_grad=True)]


In [32]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [33]:
model = nn.Linear(3,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [41]:
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

nb_epochs = 80000

for epoch in range(nb_epochs + 1):
    prediction1 = model(x_train)
    cost = F.mse_loss(prediction1,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10000 == 0:
        print('Epoch {:4d} / {} cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0 / 80000 cost : 0.157332
Epoch 10000 / 80000 cost : 0.157137
Epoch 20000 / 80000 cost : 0.157002
Epoch 30000 / 80000 cost : 0.156898
Epoch 40000 / 80000 cost : 0.156795
Epoch 50000 / 80000 cost : 0.156712
Epoch 60000 / 80000 cost : 0.156641
Epoch 70000 / 80000 cost : 0.156566
Epoch 80000 / 80000 cost : 0.156498


In [42]:
new_var = torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print(pred_y)

tensor([[151.5511]], grad_fn=<AddmmBackward>)


In [43]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0354, 0.5164, 0.4569]], requires_grad=True), Parameter containing:
tensor([0.3890], requires_grad=True)]


In [45]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
        
    def forward(self,x):
        return self.linear(x)
    
model = LinearRegressionModel()

In [46]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self,x):
        return self.linear(x)
    
model = MultiLinearRegressionModel()

In [49]:
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d} / {} cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0 / 2000 cost : 0.432470
Epoch  100 / 2000 cost : 0.428730
Epoch  200 / 2000 cost : 0.425144
Epoch  300 / 2000 cost : 0.421698
Epoch  400 / 2000 cost : 0.418378
Epoch  500 / 2000 cost : 0.415173
Epoch  600 / 2000 cost : 0.412104
Epoch  700 / 2000 cost : 0.409136
Epoch  800 / 2000 cost : 0.406283
Epoch  900 / 2000 cost : 0.403532
Epoch 1000 / 2000 cost : 0.400877
Epoch 1100 / 2000 cost : 0.398311
Epoch 1200 / 2000 cost : 0.395827
Epoch 1300 / 2000 cost : 0.393437
Epoch 1400 / 2000 cost : 0.391125
Epoch 1500 / 2000 cost : 0.388886
Epoch 1600 / 2000 cost : 0.386714
Epoch 1700 / 2000 cost : 0.384612
Epoch 1800 / 2000 cost : 0.382572
Epoch 1900 / 2000 cost : 0.380604
Epoch 2000 / 2000 cost : 0.378684
